blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: http://discord.mher.club
    about: Our support Discord, if you are unsure or you have a question please do not hesitate to seek help.
